unit testing fixes and pyFileSystem 2 support
jaraco/keyrings.alt pull request #37
Opened 2020-01-29 21:04 UTC by tcpan

Added support for pyFileSystem 2 in keyrings.alt  as my project requires both pyFS 2 and keyrings.alt.

Also fixed keyrings.alt unit tests, a lot of which were not run because they did not subclass unittest.TestCase nor followed pytest class naming conventions.

2020-09-25 08:04 UTC, mitya57 commented
@jaraco Ping!

2020-09-25 18:23 UTC, jaraco commented on keyrings/alt/pyfs.py
> -    pass
Previously, the behavior was not to raise an error when fs wasn't available. This new approach causes an ImportError when fs isn't available. That means that any users without fs installed will get an error when importing keyring. For example, I applied this diff.

```diff
diff --git a/keyrings/alt/pyfs.py b/keyrings/alt/pyfs.py
index 08addd2..cab6713 100644
--- a/keyrings/alt/pyfs.py
+++ b/keyrings/alt/pyfs.py
@@ -17,6 +17,7 @@ try:
     import fs.remote
 except ImportError:
     pass
+import doesnotexist
 
 
 def has_pyfs():
```

Then:

```
keyrings.alt master $ .tox/python/bin/python -c "import keyring"
Error initializing plugin EntryPoint(name='pyfs', value='keyrings.alt.pyfs', group='keyring.backends').
Traceback (most recent call last):
  File "/Users/jaraco/code/main/keyrings.alt/.tox/python/lib/python3.8/site-packages/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jaraco/code/main/keyrings.alt/keyrings/alt/pyfs.py", line 20, in <module>
    import doesnotexist
ModuleNotFoundError: No module named 'doesnotexist'
```

These modules are designed to be lenient to errors and to signal their viability or not through the 'priority' method.

2020-09-25 18:27 UTC, jaraco commented on keyrings/alt/pyfs.py
> +import pkg_resources
pkg_resources is discouraged for this use. Let's use importlib.metadata instead. Regardless, you need to declare the dependency.

2020-09-25 18:27 UTC, jaraco commented on keyrings/alt/pyfs.py
> +from packaging import version
Need to declare the dependency on packaging.

2020-09-25 18:36 UTC, jaraco commented on keyrings/alt/tests/backend.py
> +# coding: utf-8
Copying this file from the other project is a bad idea. It means this code will evolve independently and need to have fixes applied to both. Moreover, I can't tell from this commit whether this code was copied exactly as it appears in keyring.testing or if other changes were applied before the commit. Let's find a way to do this without copy/paste code.

2020-09-25 18:39 UTC, jaraco commented on keyrings/alt/tests/backend.py
> +# coding: utf-8
Oh, I see - much of the duplicated functionality is removed in later commits.

2020-09-25 18:41 UTC, jaraco commented on keyrings/alt/pyfs.py
> +    if FS_VER < version.parse("2.0.0"):
I'd like to see this fs compatibility behavior extracted into a module or function.

2020-09-25 18:44 UTC, jaraco commented on keyrings/alt/pyfs.py
> +        elif filename.endswith("/"):
This code seems to be changing the meaning of the filename parameter from being a filename to being a filename_or_directory, but only treating it like a directory if it ends in a posix-like slash. I don't care for that interface and I'm not sure what problem this solves. Probably this change should have its own issue and separate change.

2020-09-25 18:53 UTC, jaraco commented on keyrings/alt/pyfs.py
> +    def __del__(self):
I'm pretty sure this code is unneeded.

2020-09-25 18:56 UTC, jaraco commented on keyrings/alt/pyfs.py
> +    return FS_VER is not None
The docstring no longer matches the implementation.

2020-09-25 18:59 UTC, jaraco commented on keyrings/alt/pyfs.py
> +    _filename = 'uncrypted_pyf_pass.cfg'
Looks like this user-facing incompatible change got snuck in.

2020-09-25 19:33 UTC, jaraco commented
In #38, I've started working on the commits that fix the problems with the test suite not running due to the migration from unittest to pytest.

2020-09-25 19:58 UTC, jaraco commented
I've rebased the two pyFileSystem changes on top of the master following #38. That makes it a little easier to focus in this PR on those changes.

2020-09-25 21:20 UTC, jaraco requested changes
Thanks for the PR! I've made a few comments above. If we can address these, I'd be delighted to adopt the changes.

2020-09-25 21:22 UTC, jaraco commented on keyrings/alt/tests/test_pyfs.py
> +    keyring_root = tempfile.mkdtemp()
This directory gets created unconditionally but is only cleaned up if the tests run. Better to put this creation behavior in the _cleanup_for_fs fixture before `yield` (and rename it to match new behavior).

2020-09-25 21:23 UTC, jaraco commented on keyrings/alt/tests/test_pyfs.py
> +    @pytest.fixture(autouse=True, scope="class")
This looks like copy-pasta. Please extract into a shared fixture.

2020-09-25 21:23 UTC, jaraco commented on keyrings/alt/tests/test_pyfs.py
> +import pkg_resources
This code looks like a repeat of other code. Probably just use the code from the module.

2020-12-09 00:52 UTC, jaraco commented
Since the comments have lingered for a long time, I'm closing this languishing request, but I'm happy to revisit should interest revive.

2020-12-09 00:52 UTC, closed without merging